- .github/workflows/ci.yml
> github actions ci

- controllers/mypage.controller.js
- controllers/que.controller.js
- controllers/store.controller.js
- middlewares/auth-middleware.js
- repositories/mypage.repository.js
- repositories/que.repository.js
- routes/mypage.routes.js
- routes/que.routes.js
- services/mypage.service.js
- services/que.service.js
- services/whisky.service.js
> feat: add get whisky, storewhisky,storetable,review,que

- migrations/20230529021252-addstore.js
- models/stores.js
Stores에 address, phone, notice컬럼 추가
> add: add columns on Stores

- controllers/email.controller.js
- controllers/like.controller.js
- controllers/store.controller.js
- controllers/user.controller.js
- middlewares/auth-middleware.js
- modules/biz_photo.js
- repositories/like.repository.js
- repositories/store.repository.js
- repositories/user.repository.js
- routes/like.routes.js
- routes/user.routes.js
- services/like.service.js
- services/store.service.js
- services/user.service.js
feat: Like 기능 추가
fix: 유저 로컬,소셜로그인 활성화, 미들웨어 수정, 점주 가입 req 수정
> feat: Like 기능 추가 및 일부 기능 fix

- app.js
- migrations/20230529055025-addwhisky.js
whisky 테이블에서 whisky_abv, whisky_desc컬럼추가, whisky_taste컬럼 삭제
> add: column on whiskys

- controllers/store.controller.js
- controllers/user.controller.js
- middlewares/auth-middleware.js
> fix: 토큰 발급시 유저,스토어 정보 부분 수정

- controllers/mypage.controller.js
- controllers/que.controller.js
- controllers/store.controller.js
- controllers/whisky.controller.js
- migrations/20230529151938-addstoretime.js
- models/stores.js
- models/whiskys.js
- repositories/mypage.repository.js
- repositories/store.repository.js
- repositories/whisky.repository.js
- routes/mypage.routes.js
- services/mypage.service.js
- services/store.service.js
- services/whisky.service.js
가게상세정보 조회, 가게정보 수정기능, 위스키랑 스토어 테이블에 컬럼 추가, store관련 정보 살짝 수정
> Add:update and get store, column of Stores and Whiskys

- app.js
- controllers/whisky.controller.js
- package-lock.json
- package.json
- repositories/whisky.repository.js
- routes/whisky.routes.js
- services/whisky.service.js
위스키상세조회 관련 api추가, 에러핸들러 install 해주세용~~
> feat: add get  whisky detail,store,review and install errorhandler #5

- controllers/mypage.controller.js
- controllers/que.controller.js
- controllers/review.controller.js
- controllers/whisky.controller.js
- repositories/review.repository.js
- routes/mypage.routes.js
필요 없는 부분 수정 삭제,  error status번호 변경
> refactor: erroer status convention, refector #5 #6 #7 #8

- controllers/que.controller.js
- controllers/whisky.controller.js
- repositories/que.repository.js
- repositories/whisky.repository.js
- routes/que.routes.js
- routes/whisky.routes.js
- services/que.service.js
- services/whisky.service.js
> feat: pagenation and get myQue #5 #6

- controllers/email.controller.js
- controllers/store.controller.js
- controllers/user.controller.js
- modules/crawling.js
- routes/email.routes.js
- routes/store.routes.js
fix: 토큰 값 수정, redirect url 수정, email중복 체크 수정 #9
> fix: 토큰 값 수정, redirect url 수정, email중복 체크 수정 #9

- controllers/user.controller.js
- controllers/whisky.controller.js
- repositories/whisky.repository.js
- services/whisky.service.js
#5
유저에서 쿠키에서 유저id보내는 부분도 수정했습니다
> fix: add whisky_eng on 위스키전체조회, add whiskyLike on 위스키 상세조회

- controllers/store.controller.js
- controllers/user.controller.js
- controllers/whisky.controller.js
- modules/crawling.js
- repositories/store.repository.js
- repositories/user.repository.js
- routes/store.routes.js
- routes/user.routes.js
- routes/whisky.routes.js
- services/store.service.js
- services/user.service.js
feat: 회원탈퇴 fix: redirect 수정 #3
> fix: redirect 수정 #3

- routes/whisky.routes.js
> 6/5 2차배포 핫픽스

- controllers/whisky.controller.js
- swagger-output.json
> swagger : mypage, whisky

- controllers/mypage.controller.js
- controllers/whisky.controller.js
- repositories/whisky.repository.js
- routes/mypage.routes.js
- routes/whisky.routes.js
- services/whisky.service.js
> fix: 위스키상세조회, 스토어상세조회 #5 #7

- controllers/mypage.controller.js
- controllers/review.controller.js
- repositories/mypage.repository.js
- repositories/review.repository.js
- routes/mypage.routes.js
- routes/review.routes.js
- services/mypage.service.js
- services/review.service.js
- swagger-output.json
> fix: 중복되는 부분, 불필요url수정 #7 #8

- controllers/map.controller.js
- repositories/map.repository.js
- routes/map.routes.js
- services/map.service.js
- swagger-output.json
> feat: map get store #10

- controllers/whisky.controller.js
- repositories/whisky.repository.js
- routes/whisky.routes.js
- services/whisky.service.js
일단 전체 / 스카치=Scotland / 아메리칸=usa / 아이리시=Ireland / 그외=etc
이렇게만 필터기능 추가했습니다~
> feat: add filter on whisky #5

- controllers/mypage.controller.js
- controllers/store.controller.js
- controllers/user.controller.js
- modules/biz_photo.js
- routes/mypage.routes.js
- routes/store.routes.js
> fix: 스토어 사진 저장방식 수정#3

- repositories/mypage.repository.js
- services/mypage.service.js
좋아요한 위스키랑 리뷰남긴 위스키에 위스키정보 추가, 데이터 조회 편하도록 출력형식 수정했습니당
> fix: add whisky info on mypage #7

- controllers/review.controller.js
- repositories/mypage.repository.js
- repositories/review.repository.js
- routes/review.routes.js
- services/mypage.service.js
- services/review.service.js
- swagger-output.json
좋아요한 스토어 ->아이디 이름 사진 주소도 출력
리뷰아이디로 들어가는 api하나 만들기
localhost:3000/api/review/670
->위스키 한글, 영어, 사진, 코멘트, 좋아요부분 출력
스웨거도했슴당
> feat:get review, add mypage #7 #8 swagger

- controllers/whisky.controller.js
- repositories/whisky.repository.js
- routes/whisky.routes.js
- services/whisky.service.js
<country>
그외는 다 etc
<Scotland>
-region : 
'스페이사이드:Speyside', 
'하이랜드:Highlands',
'로우랜드:Lowlands', 
'캠벨타운:Campbeltown',
'아일라:Islay',
'그 외'
-type :
'싱글 몰트:Single Malt Whisky',
'싱글 그레인=Single Grain Whisky',
'블렌디드 몰트=Blended Malt Whisky', 
'블렌디드:Blended Whisky'
'그외'
<usa>
-type : 
'버번:Bourbon',
'라이:Rye', 
'테네시:Tennessee',
'그 외'
<Ireland>
> fix: filter, 필터api따로된거 지우고 전체검색에 쿼리문으로 변경

- swagger-output.json
> fix: swagger filter

- controllers/que.controller.js
- repositories/que.repository.js
- routes/que.routes.js
- services/que.service.js
> fix: que delete and my order dawhisky#6

- controllers/que.controller.js
- migrations/20230614020037-addcolumn.js
- models/ques.js
- repositories/que.repository.js
- services/que.service.js
- swagger-output.json
want_table column 추가하고 
hall, bar, dontCare로만 입력 가능하게 하였습니다
그리고 줄서기조회부분 없으면 빈배열 나가도록 예외처리 했습니다!
> fix: add column on Ques table and add exceptional case #6

- controllers/whisky.controller.js
- repositories/whisky.repository.js
필터부분 공백입력하면 전체로, "Japan","Canada"추가
> fix: add filter #5

- controllers/que.controller.js
- migrations/20230614145505-addcolumn.js
- models/ques.js
- repositories/que.repository.js
- services/que.service.js
> fix:add device_token column on Ques #6

- services/review.service.js
> fix:add 404error on review #8

- services/review.service.js
위스키 리뷰내용 없으면 위스키 정보만 뜨고 내용은 아무것도 안뜨게했슴당
> fix:review #8

- controllers/mypage.controller.js
- repositories/mypage.repository.js
- routes/mypage.routes.js
- services/mypage.service.js
> feat:mypage getmyque #7

- repositories/mypage.repository.js
- services/mypage.service.js
> fix: add store on mypage que #7

- repositories/mypage.repository.js
- services/mypage.service.js
> fix: add myTurn que on #7

- controllers/whisky.controller.js
- repositories/whisky.repository.js
- routes/whisky.routes.js
- services/whisky.service.js
검색으로 상세페이지 들어가는부분 api새로 만들기로!!->쿼리 ?search=y 추가 
위스키 인기검색어 조회 
/api/whisky/trending
초보자를 위한 추천 조회 
/api/whisky/beginner
위스키목록 조회 시 페이지네이션에서 마지막을 표시하기 위한 last:true추가 
1. 글렌모렌지 오리지널(glenmorangie original)	-1241
2. 글렌피딕 12년(glenfiddich 12y)			-775
3. 발베니 12년(balvenie 12y)더블우드		-745
4. 보모어 12년(bow more 12y)			-757
5. 글렌킨치 12년(glenkinchie 12y)			-829
6. 하이랜드 파크 12년(highland park 12y)		-742
7. 글렌드로낙 12년(glendronach 12y)		-1120
8. 메이커스 마크(maker’s mark)			-796
9. 와일드 터키101(wild turkey 101)		-891
10. 제임슨 스탠다드(Jameson standard)		-1230
11. 캐내디언 클럽 12년(Canadian club 12y)		-1351
12. 버팔로 트레이스(buffalo trace)		-980
13. 페이머스 그라우스(famous grouse)		-1121
14. 조니워커 블랙라벨(Johnnie walker black label)	-959
15. 오반 14년(oban 14y)				-774
> feat:유저피드백 반영2 #5

- swagger-output.json
> fix:swagger

- controllers/whisky.controller.js
- repositories/whisky.repository.js
- services/whisky.service.js
- swagger-output.json
위스키 코멘트조회에 내껀지아닌지 넣었고
스웨거도 살짝 수정했습니다~
> fix: add mine? on whisky comment #5
